config/routes.rb
Rails.application.routes.draw do
  resources :clients
  get 'clients/success'
  get 'registrations/new'
  post 'registrations/signup'
  get 'sessions/new'
  post 'sessions/authenticate'
  get 'sessions/landing_page'
  root 'clients#index'
  get 'sessions/new'

  namespace :api do
    namespace :v1 do
      resources :clients
    end
  end

  mount API => '/'

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
    @signup = Signup.all
  end

  def new
    @signup = Signup.new
  end

  def show; end

  def create
    p 'Hellooooooooo-----------'
    @signup = Signup.new(signup_params)
    Rails.logger.debug "Signup--user: #{@signup.inspect}"
    user = @signup.save
    Rails.logger.debug "USer: #{user.inspect}"
    # if @signup.save
    #   redirect_to 'show'
    #  else
    #    render 'new'
    #  end
  end

  private

  def signup_params
    params.require(:signup).permit(:username, :password, :confirmpwd)
    end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/index.html.erb
<h1>Signup</h1>

<form accept-charset="UTF-8" action="/signup/index" method="get">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <label for="username">Username:</label>
  <input id="username" name="username" type="text" /><br/>
  <label for="password">Password:</label>
  <input id="password" name="password" type="text" /><br/>
  <label for="confirmpwd">Confirm:</label>
  <input id="confirmpwd" name="confirmpwd" type="text" /><br/>
  <input name="commit" type="submit" value="Save" />
</form>

app/views/signup/new.html.erb
<h1>Signup</h1>

<%= form_for @signup, url: signup_show_path, html: { method: :get } do |f| %>
  <p>
  <label>Username</label><br>
  <%= f.text_field :username %>
</p>
<p>
  <label>Password</label><br>
  <%= f.password_field :password %>
</p>

<p>
  <label>Confirm Password</label><br>
  <%= f.password_field :confirmpwd %>
</p>
<br>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/signup/show.html.erb
<h1>Signup</h1>

<h3>Hello</h3>
<input name="logout" type="submit" value="Logout" />